/*
Description: This is a program to generate a random array given a certain seed and print the array, 
find the arrays average value, largest element, how many 3s occur, count how many elements are less 
than half the first index, and many numbers repeat in the sequence, and swap the first and last values.
*/
import java.util.Random;
import java.util.Scanner;
public class Minilab_2 {

	public static void main(String[] args) {
			//Object that receives input from the keyboard
		Scanner input = new Scanner(System.in);
		
			//Variable to set the seed for creating the numbers in the array
		System.out.println("Please enter a seed:");
			int seed = input.nextInt();
			
			//Enter the size of the array
		System.out.println("Please enter the size of the array:");
				int size = input.nextInt();
				
			//Re-enter array size value must be greater than 1
		while(size <= 1)
		{
			System.out.println("Array size must be greater than 1.  Please reenter:");
				size = input.nextInt();
		}
			//Initialize array and fill with values generated by the seed
		int [] array = new int[size];
		Random generator = new Random(seed);
		for (int i = 0; i < array.length ; i++){
			array[i] = generator.nextInt(9);
		}
			//List of options to select from to do calculations with the array
		int option;
		do{
			
			System.out.println("\nPlease choose an option:");
				System.out.println("1. Print the array");
				System.out.println("2. Find the average");
				System.out.println("3. Find the largest element");
				System.out.println("4. Count how many times 3 occurred");
				System.out.println("5. Count how many elements are less than half of the first element");
				System.out.println("6. Find how many times numbers repeat consecutively");
				System.out.println("7. Swap the first and last elements");
				System.out.println("8. Exit");
			
			
			option = input.nextInt();
		switch(option)
		{
			case 1:		//Prints out array
				System.out.print("\nArray:  ");
				for(int i = 0; i < array.length; i++)
					System.out.print(array[i] + " ");
				
				break;
			case 2:		//Calculates the average of all the arrays values
				double sum = 0;
				for(int i = 0; i < array.length; i++) {
					sum = sum + array[i];}
				double average = (sum / array.length);
				System.out.println("\nAverage: " + average);
				
				break;
			case 3:		//Finds largest value in the array
				int max = array[0];
				for(int i = 0; i < array.length-1; i++) {
					if(array[i] > max) {
						max = array[i];
					}
				}
				System.out.println("Largest: " + max);
				break;
			case 4:		//Count how many times 3 is in the array
				int test = 0;
				for(int i = 0; i < array.length; i++) {
					if(array[i] == 3 ){
						test++;
					}
				}
				System.out.println("3Count: " + test);
				break;
			case 5:		//Number of elements that are less than half the [0] index of the array
				int test1 = 0;
				double halfAmount = (array[0] / 2.0);
				for(int i = 0; i < array.length; i++) {
					if(array[i] < halfAmount){
						test1++;
					}
				}
				System.out.println("Less than half of first: " + test1);
				break;
			case 6:		//Counter for how many times a number is consecutively repeated 
				
				int counter = 0;
				for(int i = 0; i < array.length-1; i++) {
					if(array[i] == array[i+1]){
						counter++;
					}
				}
				System.out.print("\nRepeats: " + counter);
				
					
				break;
			case 7:		//Swaps the first and last indexes of the array
				int swap = array[0];
				array[0] = array[array.length-1];
				array[array.length-1] = swap;
				System.out.print("Array:  ");
				for(int i = 0; i < array.length; i++)
					System.out.print(array[i] + " ");
				break;
			case 8:		//Exit the loop
				break;
			default:
	        	 System.out.print("\nIllegal option, try again");
		}
		
		}while(option != 8);
		
	}

}
